/* 
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api.Client.Sdk.Api;
using Api.Client.Sdk.Model;
using Api.Client.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api.Client.Sdk.Test
{
    /// <summary>
    ///  Class for testing WeatherForecast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WeatherForecastTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WeatherForecast
        //private WeatherForecast instance;

        public WeatherForecastTests()
        {
            // TODO uncomment below to create an instance of WeatherForecast
            //instance = new WeatherForecast();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WeatherForecast
        /// </summary>
        [Fact]
        public void WeatherForecastInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WeatherForecast
            //Assert.IsInstanceOfType<WeatherForecast> (instance, "variable 'instance' is a WeatherForecast");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'TemperatureC'
        /// </summary>
        [Fact]
        public void TemperatureCTest()
        {
            // TODO unit test for the property 'TemperatureC'
        }
        /// <summary>
        /// Test the property 'TemperatureF'
        /// </summary>
        [Fact]
        public void TemperatureFTest()
        {
            // TODO unit test for the property 'TemperatureF'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

    }

}
